### ISSUE TITLE
iOS 15

### ISSUE THREAD

**Issue by scotthmusson** [chemerisuk/cordova-plugin-idfa#19]
On iOS 15 calling dfaPlugin.requestPermission() no dialog is shown.  It works fine on iOS 14.8 and below.

I agree with the comments below, this is not an issue with the plugin, sorry I didn't realize it sooner.

**Comment by rkkhadka90** [comment]
absolutely, we need some help here if this repo is still managed, please!

**Comment by mattyc246** [comment]
The issue is not with the plugin but actually due to the way the ATT is implemented. In iOS 15 they have prevented stacking of prompts so if you have another prompt being called before it, it won't get queued and inevitably won't get shown.

```
Calls to the API only prompt when the application state is UIApplicationStateActive. The authorization prompt doesn’t display if another permission request is pending user confirmation. Concurrent requests aren’t preserved by iOS, and calls to the API through an app extension don’t prompt. Check the trackingAuthorizationStatus for a status of ATTrackingManager.AuthorizationStatus.notDetermined to determine if you need to make an additional call.`
```

You can check out this thread on Apple Developer forum.

https://developer.apple.com/forums/thread/690607?answerId=689399022#689399022

I can still see the prompt by dismissing the first prompt that blocks it and then reloading the app.

**Comment by rkkhadka90** [comment]
@mattyc246 Thanks for the info Matt,

Not sure if there's a work around but my problem arises if:
1. Use doesn't resolve request for push notification before ATT prompt is called. And I can't intercept the callback on pushNotification because I have implemented Salesforce Marketing cloud for Push (it doesn't provide API to request push notification instead makes a request by itself first thing when the app loads)

Looking forward to your thoughts on this.

**Comment by mattyc246** [comment]
@rkkhadka90 I have found a workaround that is within the guidelines from Apple.

https://developer.apple.com/design/human-interface-guidelines/ios/app-architecture/accessing-user-data/

First I checked the value of the `idfa.trackingPermission` and if it is `idfa.TRACKING_PERMISSION_NOT_DETERMINED` then I will display a full page overlay that outlines why we use tracking (you can see the examples in the apple interface guidelines).

I will still get the location and notification appear over the top but once I have dismissed them I will be left with the overlay and I can then trigger the `idfa.requestPermission` by clicking the continue button and there is no other way around the overlay.

It's not the most elegant way to do it, but it does prevent the `requestPermission` from being blocked by the notification or location prompts.

Hope this helps you out too.

**Comment by rkkhadka90** [comment]
@mattyc246 Thanks a lot, I will definitely check this out and in fact I am trying to do something similar like showing ATT prompt only when a certain page is resolved.

**Comment by scotthmusson** [comment]
I would like to withdraw this issue, it is my mistake, sorry for the issue.  I agree with the comments of others.

**Comment by rkkhadka90** [comment]
yes that could definitely work as well.
________________________________
